language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "node"
  - "iojs-v1.0"
  - "iojs-v1.1"
  - "iojs-v1.2"
  - "iojs-v1.3"
  - "iojs-v1.4"
  - "iojs-v1.5"
  - "iojs"
services:
- rabbitmq
deploy:
  provider: npm
  email: engineering@lanetix.com
  api_key:
    secure: UFa+1JCFzX+iMsARDFgZ9+y1qLaJt1Yn4kCLOyQ1XpH1sY2J7ClhxUra5qURmWwUIXWrI65DyZzyp1cgHo/FbWNv1adMsd0FjMIe+I5yq+6fdNVWXTtoVh/vdZcbr36lIZAW9gpXGaR41vBTd5bLxt1C6iM+Dlfvex2Nxy0aC8U=
  on:
    repo: lanetix/node-amqplib-retry
    branch: master
